name: Platformatic PR Previews
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  build_and_deploy:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'sqlite://./db.sqlite'
      PLT_SERVER_LOGGER_LEVEL: info 
      PORT: 3001 
      PLT_SERVER_HOSTNAME: 127.0.0.1 

    steps:
      - name: Checkout application project repository
        uses: actions/checkout@v4
      - name: npm install --omit=dev
        run: npm install --omit=dev
      - name: Deploy project
        id: deploy-project
        uses: platformatic/onestep@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_workspace_id: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_ID }}
          platformatic_workspace_key: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_API_KEY }}
          platformatic_config_path: ./platformatic.runtime.json
    outputs:
      deployment_id: ${{ steps.deploy-project.outputs.deployment_id }}

  calculate_risk:
    permissions:
      contents: read
      pull-requests: write
    needs: build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Calculate risk
        uses: platformatic/onestep/actions/calculate-risk@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_workspace_id: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_ID }}
          platformatic_workspace_key: ${{ secrets.PLATFORMATIC_DYNAMIC_WORKSPACE_API_KEY }}
          platformatic_deployment_id: ${{ needs.build_and_deploy.outputs.deployment_id }}
